version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/code
      - ./service-account.json:/code/app/service-account.json
    ports:
      - 8000:80
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB_NAME=fastapi_db_v2
      - GOOGLE_APPLICATION_CREDENTIALS=/code/app/service-account.json
      - SMTP_USER=no-reply@morseverse.com
      - SMTP_PASSWORD=Qarjej-6feqga-toxmev
      - SMTP_HOST=smtp.ionos.it
      - SMTP_PORT=587
      - EMAIL_FROM=no-reply@morseverse.com
      - EMAIL_FROM_NAME=Morseverse
      - SECRET_KEY=_RgL9B_@CTTxFEs!&:j5,,qS'DU?dT
      - MONGODB_DB_NAME_SPETIAL_AI=specialAI
      - GCS_BUCKET_NAME=morse-sample-data
      - GCS_FILE_PATH=coordinates/coordinates.json
      - AI_SITE=https://morseverse.com/ai_agent
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: